Repository playcanvas/editor-api, pull requests merged in 2021-11, with the labels that each got.

#23 Added functions to instantiate template assets
  src/asset.js
  src/assets.js
  src/assets/instantiateTemplates.js
  test/api/test-assets.js
Labels: enhancement

#22 Added addScript and removeScript functions to entities api
  src/entities.js
  src/entities/duplicate.js
  src/entities/scripts.js
  src/entity.js
  test/api/test-entity.js
  test/lib/schema.js
Labels: enhancement

#26 Lint fixes
  .eslintrc.json
  src/entities/paste.js
  src/realtime/connection.js
Labels: enhancement

#29 Asset replace
  docs/README.md
  docs/classes/Asset.md
  docs/classes/AssetProperties.md
  docs/classes/Assets.md
  docs/classes/AssetsSchema.md
  docs/classes/Clipboard.md
  docs/classes/ComponentSchema.md
  docs/classes/Entities.md
  docs/classes/Entity.md
  docs/classes/EntityProperties.md
  docs/classes/Guid.md
  docs/classes/History.md
  docs/classes/Jobs.md
  docs/classes/LocalStorage.md
  docs/classes/Messenger.md
  docs/classes/Realtime.md
  docs/classes/RealtimeAsset.md
  docs/classes/RealtimeAssets.md
  docs/classes/RealtimeConnection.md
  docs/classes/RealtimeScene.md
  docs/classes/RealtimeScenes.md
  docs/classes/SceneSettings.md
  docs/classes/SceneSettingsProperties.md
  docs/classes/Schema.md
  docs/classes/Selection.md
  docs/classes/SelectionHistory.md
  docs/classes/Settings.md
  docs/classes/globals.md
  docs/classes/utils.md
  docs/interfaces/AssetUploadArguments.md
  docs/interfaces/CreateEntityArguments.md
  docs/interfaces/HistoryAction.md
  docs/interfaces/ReparentArguments.md
  docs/interfaces/SceneImportSettings.md
  docs/interfaces/TextureImportSettings.md
  docs/modules.md
  index.js
  package-lock.json
  package.json
  src/asset.js
  src/assets/replace.js
  src/entities/references.js
  src/globals.js
  src/realtime/asset.js
  src/schema/assets.js
  src/settings.js
  src/settings/scene.js
  src/utils.js
  test/api/test-asset.js
  test/api/test-utils.js
  test/lib/schema.js
Labels: enhancement

#30 More logs to track missing guids bug
  package-lock.json
  package.json
  src/entities/reparent.js
  src/entity.js
Labels: bug, enhancement

#31 Fix duplicate nested template
  docs/classes/Asset.md
  docs/classes/Assets.md
  docs/classes/AssetsSchema.md
  docs/classes/Clipboard.md
  docs/classes/ComponentSchema.md
  docs/classes/Entities.md
  docs/classes/Entity.md
  docs/classes/Guid.md
  docs/classes/History.md
  docs/classes/Jobs.md
  docs/classes/LocalStorage.md
  docs/classes/Messenger.md
  docs/classes/Realtime.md
  docs/classes/RealtimeAsset.md
  docs/classes/RealtimeAssets.md
  docs/classes/RealtimeConnection.md
  docs/classes/RealtimeScene.md
  docs/classes/RealtimeScenes.md
  docs/classes/SceneSettings.md
  docs/classes/Schema.md
  docs/classes/Selection.md
  docs/classes/SelectionHistory.md
  docs/classes/Settings.md
  docs/classes/globals.md
  docs/classes/utils.md
  docs/interfaces/AssetUploadArguments.md
  docs/interfaces/CreateEntityArguments.md
  docs/interfaces/HistoryAction.md
  docs/interfaces/ReparentArguments.md
  docs/interfaces/SceneImportSettings.md
  docs/interfaces/TextureImportSettings.md
  package-lock.json
  package.json
  src/entities/duplicate.js
  test/api/test-entities.js
Labels: bug

#32 Fix missing thumbnails
  package-lock.json
  package.json
  src/asset.js
Labels: bug
